services:
  canvas-docker:
    image: orlissenberg/canvas-lms:latest
    ports:
      # Syntax HOST:CONTAINER
      - "3000:3000"
      # Postgresql
      - "5434:5432"
      # Redis
      - "6380:6379"
      # HAProxy
      - "8443:8443"
    networks:
      - canvas

networks:
  canvas: { }
